### PR TITLE
ENH: Update VTK Ghost API

### PR DESCRIPTION
**Pull request by Patol75**
This PR is a port of changes originally written for this [commit](https://github.com/FluidityProject/fluidity/commit/75d59c6c06c1a0dadc485f525f9f9024c133c922); hopefully, I did not break too many things in the process.

The purpose of this PR is to reflect already [old changes in the VTK API](https://www.kitware.com/ghost-and-blanking-visibility-changes/) regarding ghosts. Currently, loading a Fluidity PVTU on recent versions of ParaView or using VTK bindings for Python will generate as many error messages as CPU cores were used, which is not a good sign. Furthermore, pvtu2vtu is broken when attempting to generate multiple VTUs at once.

The changes included in this PR should correct these issues. The idea is for the CI to stay green and for the reviewer(s) to generate a parallel model using this branch and assert that results can be properly loaded into ParaView and that pvtu2vtu works.

To review the changes, please have a look at the second commit attached; the first one only deals with formatting, no changes were applied.

### CODE REVIEW

**Review by gnikit — COMMENTED** [review]
LGTM I would consider adding at a later point black and isort in the dev dependencies of setup.cfg /pyproject.toml along with some other things like precommit. I think there is a PR switching to setuptools #351 

I will however leave the approval of this PR to someone else.

**Review by angus-g — CHANGES_REQUESTED** [review]
Interface changes look fine, but let's leave out the whitespace and formatting changes for now. As @gnikit suggested, the Black formatting could come into a separate CI change. I think the Fortran is sufficiently crufty that it's not worth doing a wholesale formatting change.

**Comment by Patol75** [comment]
@angus-g This one is actually a massive pain to rebase, mostly because of the Python formatting changes. Any chance to proceed as-is?

**Review by angus-g — APPROVED** [review]
I guess so. It would be nice to get the large-scale formatting done then so we don't keep running into this.

**Comment by Patol75** [comment]
Thanks, @angus-g.

I have just pushed a pre-commit branch. For now, all I have done is patch files using information detailed [here](https://pre-commit.com/). CI should follow based on [this](https://pre-commit.ci/). Actions run will be [here](https://github.com/FluidityProject/fluidity/actions/runs/2620971692).

**Comment by angus-g** [comment]
Hmm, I rebased this onto main just to get the PR in, but it seems like the [new test failure](https://github.com/FluidityProject/fluidity/runs/7208629853?check_suite_focus=true#step:2:247) is at least somewhat real?

**Comment by Patol75** [comment]
This test passed in the previous Actions run. Additionally, I remember seeing similar errors when I went through all the tests for the CMake build. Unfortunately, I do not remember what I did in that case if anything. I cannot see any major changes for that particular test in the CMake branch, and I do not think that the changes in the present branch affect this test at all. I am thinking it could well turn green if triggered again.

**Comment by Patol75** [comment]
Thanks @angus-g, all green :)

**Pull request merged**
