### PR TITLE
Failing tests on Ubuntu 18.04 Bionic

### PR DESCRIPTION
**Pull request by Patol75**
Dear all,

Following #192, I have created a branch https://github.com/FluidityProject/fluidity/tree/FixTests to fix the few tests that fail.
For now, I have not looked through the ```make unittest``` call.
For the ```make test``` call, ```mmat-interpolation-2d-parallel.xml``` and ```square-convection-parallel-trivial.xml``` fail because of an assertion at line 209 in femtools/Intersection_finder.F90. I considered it to be unnecessary (which may not be true) and thereby I commented it, which allowed both tests to pass (apologies for the diff result, my text editor automatically gets rid of the white spaces on blank lines). ```coarse-corner-limited.xml``` fails to achieve an error smaller than 1e-1 for the last part of the test; it results in a 1.01e-1 value on my machine. Do you think refining the mesh would be an acceptable fix ?
For the ```make mediumtest``` call, ```square-convection-parallel.xml``` fails for the exact same reason stated above and is able to pass after the proposed fix. All the ```popbal_nonhomog``` fail because a real variable is used as an index of a Python list / Numpy array, which is fixed by a call to the Python ```int``` built-in function. I did not look through ```diamond_validation.xml```, but it also fails.

I am willing to investigate the tests that still fail, however my limited knowledge of Fortran may prevent me from succeeding in fixing them all, therefore please feel free to have a look at them as well.

Thomas

### CODE REVIEW

**Comment by jrper** [comment]
I think it's possible that the assert is designed to protect against possible memory leaks caused by the next line clobbering the existing contents of that variable. Possibly @stephankramer or @jrmaddison might be able to confirm. What's slightly more worrying is that the behaviour has changed, which might either be another instability in the bionic compiler, or a subtle initialisation problem which we hadn't seen previously.

**Comment by jrmaddison** [comment]
> at line 209 in femtools/Intersection_finder.F90

The code here starts with a series of 'seed' elements at which to start the advancing front intersection finder, which should all be in distinct connected sub-meshes of mesh A.

The assertion on line 209 checks that the i th element of mesh A, which has been determined to have intersections with one or more elements from mesh B, has not already been determined to have intersections with elements from mesh B. This could happen, for example, if the seed elements were not in distinct connected sub-meshes of mesh A, and I think a failure would always indicate a bug.

**Comment by Patol75** [comment]
Thank you for the details. Looking into the issue, the while loop inside which the assertion is written depends on the association of the pointer node. Declaring it this way ```type(inode), pointer :: node => null()``` and associating it this way ```node => seeds%firstnode```, its value is always 1 when entering the while loop. When re-associating it through ```node => node%next```, its value becomes 0 and the while loop exits. However, in the case when the assertion fails, the value of node after re-association is 9 and the while loop does not exit. As the variable map_AB is not modified at the end of the while loop and the index i of the inner do loop is reset to 1, a new iteration of the while loop means that the assertion ```assert(map_AB(i)%length == 0)``` inside the inner do loop will inevitably fail. This means that either way i should not be reset to 1, either way map_AB should be modified after the end of the do loop but before the end of the while loop, either way there should not be a second iteration of the do while loop (which questions its existence).

**Comment by stephankramer** [comment]
This appears to be a compiler bug as well: in the result returned from advancing_front_intersection_finder() the components of the type(ilist) array are not (re)initialised, meaning that in the following line:

      sub_map_AB = advancing_front_intersection_finder(positionsA, positionsB, seed = node%value)

sub_map_AB retains its original entries, unless explicitly overwritten in advancing_front_intersection_finder() by new intersections found in the current subdomain. In particular %length is not reset to 0. This is incorrect as the derived type definition reads:

    TYPE ilist
       integer :: length=0
       TYPE (inode), POINTER :: firstnode=>null()
       type(inode), pointer ::  lastnode => null()
    END TYPE ilist

I've submitted a bug here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85750

Unfortunately this seems a rather serious bug as we depend on derived type component initialization in quite a few places in the code

**Comment by jrper** [comment]
Good spot. At least that one doesn't seem to be operating system dependent.

**Comment by jrper** [comment]
Some playing around suggests that adding `map_AB%length = 0` to the beginning of `advancing_front_intersection_finder` would indeed be another workaround, and possibly easier to defend than temporarily silencing the assert. @stephankramer how do you feel about us doing that until your bug report get's proper attention?

**Comment by Patol75** [comment]
Good catch indeed @stephankramer.
The bug report has been answered as a behaviour change for now. I imagine it can make sense that the output declaration in a function does not explicitly re-declare and initialize the variable, as it is supposed to have already been done somewhere else in the code; it would just stand as some kind of an extra security check for the compiler. However, I am very puzzled with the fact that this behaviour only occurs if the defined type includes a pointer declaration as you mentioned it. Does it make sense to anybody ? In any case, the output of ```print *, loc(mylist%count)``` does not change whenever it is called in the program.

**Comment by jrper** [comment]
Looking into the bionic unittest failures, they're mostly connected to the intersection finder issue, expect `test_matmul_t` and `test_simplex_tensor_edgelens`. In the first case we now get a machine precision error comparing hand rolled sparse multiplication to a matmul on dense matrices, while in the second a tolerance tested as smaller that 200.0*epsilon(0.0) is now hitting that limit pretty precisely. 

I'd be willing to ascribe the first to gfortran doing something more intelligently in matmuls now, but I don't feel qualified to to comment on the second.

**Comment by stephankramer** [comment]
Had a quick look at the second: with gcc-7.3 it passes, but only just (with 100 epsilon it fails). So seems sensible to just loosen the tolerance a bit. The computation seems to involve some inversion and eigenvalue de and recomposition, so I'm not too surprised it having some round off.

**Comment by Patol75** [comment]
Please do, happy to see that everything looks sorted now ! Ubuntu has just started offering the upgrade from 17.10 to 18.04, we are on time !

**Comment by jrper** [comment]
I've pushed the changes here, including noting what was going on to have diamond_validation failing (an additional file is being created once the full test suite is run, which is why I wasn't spotting it before).

Unfortunately, we have a new medium test failure in `gls-Kato_Phillips-mixed_layer_depth` where `gls-Kato_Phillips-mixed_layer_depth-gen-GL.flml` fails with a solver failure and then a Seg fault. I can't spot anything immediately obvious, and I don't think this was in @Patol75' s original list of failures, so I'm not totally what's going on. @stephankramer, any chance you could take a swift look, and cast an eye over the rest?

**Comment by stephankramer** [comment]
Hm, I can't reproduce. This is in a bionic container with fluidity master (only with the Futils reorder), built with debugging. Did you build with debugging? Or should I try with the branch with all fixes in?

**Comment by jrper** [comment]
I'm getting it with the branch now attached to this PR, on a bionic container.

**Comment by Patol75** [comment]
Updating the branch on my 18.04 install, fluidity builds, make unittest passes, make test returns one failure and make mediumtest is still running...
For make test, ```coarse-corner-limited.xml``` is the one failing, but that has already been reported in the first comment of this pull request and it is just an accuracy problem.
```
coarse-corner-limited: Running Correct adapted node count:
Asserting max relative error is smaller than 0.1
max relative error: 0.101928374656; index: 1
coarse-corner-limited: failure.
```
Having a look solely at ```gls-Kato_Phillips-mixed_layer_depth-gen-GL.flml```, it passes.
```
thomas@tristan:~/Softwares/fluidity/tests$ ../tools/testharness.py -f gls-Kato_Phillips-mixed_layer_depth.xml
fluidity
--------------------------------------------------------------------------------
which fluidity: /home/thomas/Softwares/fluidity/bin/fluidity
Revision: FixTests:54d78c4340241ac24d45906358a1339cb527222b (debugging)
Compile date: May 16 2018 08:38:28
OpenMP Support			no
Adaptivity support		yes
2D adaptivity support		yes
3D MBA support			no
CGAL support			no
MPI support			yes
Double precision		yes
NetCDF support			yes
Signal handling support		yes
Stream I/O support		yes
PETSc support			yes
Hypre support			yes
ARPACK support			no
Python support			yes
Numpy support			yes
VTK support			yes
Zoltan support			yes
Memory diagnostics		yes
FEMDEM support			no
Hyperlight support		no
libsupermesh support		no
--------------------------------------------------------------------------------
 
gls-Kato_Phillips-mixed_layer_depth: Running
gls-Kato_Phillips-mixed_layer_depth: Calling 'make input':
rm -f src/*.msh *.ele *.edge *.node *.face *.poly *.vtu *.s  *.stat *.log-0 *.err-0 matrixdump*
gmsh -2 ./src/KatoPhillips-2D-periodic.geo
Info    : Running 'gmsh -2 ./src/KatoPhillips-2D-periodic.geo' [Gmsh 3.0.6, 1 node, max. 1 thread]
Info    : Started on Wed May 16 20:36:05 2018
Info    : Reading './src/KatoPhillips-2D-periodic.geo'...
Info    : Done reading './src/KatoPhillips-2D-periodic.geo'
Info    : Finalized high order topology of periodic connections
Info    : Meshing 1D...
Info    : Meshing curve 1 (extruded)
Info    : Meshing curve 2 (extruded)
Info    : Meshing curve 3 (extruded)
Info    : Meshing curve 4 (extruded)
Info    : Done meshing 1D (3e-05 s)
Info    : Meshing 2D...
Info    : Meshing surface 5 (extruded)
Info    : Done meshing 2D (0.00019 s)
Info    : 104 vertices 210 elements
Info    : Writing './src/KatoPhillips-2D-periodic.msh'...
Info    : Done writing './src/KatoPhillips-2D-periodic.msh'
Info    : Stopped on Wed May 16 20:36:05 2018
cp src/KatoPhillips-2D-periodic.msh .
gls-Kato_Phillips-mixed_layer_depth: 
            fluidity gls-Kato_Phillips-mixed_layer_depth-gen-GL.flml
            fluidity gls-Kato_Phillips-mixed_layer_depth-k_w-CB.flml
        
gls-Kato_Phillips-mixed_layer_depth: Assigning variables:
gls-Kato_Phillips-mixed_layer_depth: Assigning FinalTimeGenGL = 36029.1268053
gls-Kato_Phillips-mixed_layer_depth: Assigning FinalTimeKWCB = 36029.1268053
gls-Kato_Phillips-mixed_layer_depth: Assigning GenGL_MLD = ([4.0080907792579747, 4.6080907792579735, 6.1080907792579735, 7.8080907792579737, 9.8080907792579737], [13.0, 15.0, 17.0, 19.0, 21.0], [12.464054675562446, 13.364449793861086, 15.386622976978813, 17.396544717016624, 19.49767420015109])
gls-Kato_Phillips-mixed_layer_depth: Assigning KWCB_MLD = ([4.0080907792579747, 4.5080907792579747, 6.0080907792579739, 7.708090779257974, 9.708090779257974], [13.0, 15.0, 17.0, 19.0, 21.0], [12.464054675562446, 13.218643717735556, 15.260150395048159, 17.284784972193176, 19.398023679205917])
gls-Kato_Phillips-mixed_layer_depth: Running failure tests: 
gls-Kato_Phillips-mixed_layer_depth: Running Final time equals 10 hours for Gen GL:
gls-Kato_Phillips-mixed_layer_depth: success.
gls-Kato_Phillips-mixed_layer_depth: Running Final time equals 10 hours for k-w CB:
gls-Kato_Phillips-mixed_layer_depth: success.
gls-Kato_Phillips-mixed_layer_depth: Running MLD for Gen GL vs analytical:
gls-Kato_Phillips-mixed_layer_depth: success.
gls-Kato_Phillips-mixed_layer_depth: Running MLD for K-W CB vs analytical:
[ 0.53594532  1.78135628  1.7398496   1.71521503  1.60197632]
gls-Kato_Phillips-mixed_layer_depth: success.
gls-Kato_Phillips-mixed_layer_depth: PPPP
Passes:   4
Failures: 0
Warnings: 0
```

**Comment by jrper** [comment]
Thanks for the update @Patol75. Based on the investigations here, it looks like `coarse-corner-limited` is failing for you, but not in a container, while `gls-Kato_Phillips-mixed_layer_depth` is failing in a release build but not with debugging enabled (thanks @stephankramer).

Comparing the versions of fluidity I have to hand, it looks like the relative error in `coarse-corner-limited` increases (deterministically) with gcc version and again with the switch to bionic (in a container). I'm not sure precisely what on your system is enough to increase the error past the test limit, so I'm loath to suggest increasing the tolerance until we understand what's changed.

**Comment by Patol75** [comment]
And as a complement, this is what ```mediumtest``` returns:
```
Summary of test problems with failures or warnings:
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d.xml: PPPPFPPPPPPPP

Passes:   1558
Failures: 1
Warnings: 0
```
However when I run the test single, I get:
```
thomas@tristan:~/Softwares/fluidity/tests$ ../tools/testharness.py -f 3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d.xml
fluidity
--------------------------------------------------------------------------------
which fluidity: /home/thomas/Softwares/fluidity/bin/fluidity
Revision: FixTests:54d78c4340241ac24d45906358a1339cb527222b (debugging)
Compile date: May 16 2018 08:38:28
OpenMP Support			no
Adaptivity support		yes
2D adaptivity support		yes
3D MBA support			no
CGAL support			no
MPI support			yes
Double precision		yes
NetCDF support			yes
Signal handling support		yes
Stream I/O support		yes
PETSc support			yes
Hypre support			yes
ARPACK support			no
Python support			yes
Numpy support			yes
VTK support			yes
Zoltan support			yes
Memory diagnostics		yes
FEMDEM support			no
Hyperlight support		no
libsupermesh support		no
--------------------------------------------------------------------------------
 
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Running
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Calling 'make input':
rm -rf *.msh *.stat *.vtu *.node *.ele *.edge *.log-0 *.err-0 *checkpoint *.convergence
gmsh -3 -bin cube.geo
Info    : Running 'gmsh -3 -bin cube.geo' [Gmsh 3.0.6, 1 node, max. 1 thread]
Info    : Started on Thu May 17 08:12:59 2018
Info    : Reading 'cube.geo'...
Info    : Done reading 'cube.geo'
Info    : Finalized high order topology of periodic connections
Info    : Meshing 1D...
Info    : Meshing curve 1 (extruded)
Info    : Meshing curve 2 (extruded)
Info    : Meshing curve 3 (extruded)
Info    : Meshing curve 4 (extruded)
Info    : Meshing curve 7 (extruded)
Info    : Meshing curve 8 (extruded)
Info    : Meshing curve 9 (extruded)
Info    : Meshing curve 10 (extruded)
Info    : Meshing curve 12 (extruded)
Info    : Meshing curve 13 (extruded)
Info    : Meshing curve 17 (extruded)
Info    : Meshing curve 21 (extruded)
Info    : Done meshing 1D (0.000116 s)
Info    : Meshing 2D...
Info    : Meshing surface 5 (extruded)
Info    : Meshing surface 14 (extruded)
Info    : Meshing surface 18 (extruded)
Info    : Meshing surface 22 (extruded)
Info    : Meshing surface 26 (extruded)
Info    : Meshing surface 27 (extruded)
Info    : Done meshing 2D (0.001697 s)
Info    : Meshing 3D...
Info    : Meshing volume 1 (extruded)
Info    : Subdividing extruded mesh
Info    : Swapping 0
Info    : Remeshing surface 5
Info    : Meshing surface 5 (extruded)
Info    : Remeshing surface 14
Info    : Meshing surface 14 (extruded)
Info    : Remeshing surface 18
Info    : Meshing surface 18 (extruded)
Info    : Remeshing surface 22
Info    : Meshing surface 22 (extruded)
Info    : Remeshing surface 26
Info    : Meshing surface 26 (extruded)
Info    : Done meshing 3D (0.009347 s)
Info    : Optimizing 3D mesh...
Info    : Done optimizing 3D mesh (0.000131 s)
Info    : 756 vertices 4028 elements
Info    : Writing 'cube.msh'...
Info    : Done writing 'cube.msh'
Info    : Stopped on Thu May 17 08:12:59 2018
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: 
fluidity -v1 -l 3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d.flml 

3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Log: fluidity.err-0
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d:  Warning:make_quadrature: degree            4  requested but            5 available.
[...]
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d:  Warning:make_quadrature: degree            4  requested but            5 available.
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: 
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning variables:
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning endtime = 0.435530816894
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning endtimestep = 0.0129925644835
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning mindivergence = 1.39042795135e-09
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning maxdivergence = 9.12227882518e-10
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning vfracintwater0 = 2.05138888889
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning vfracintwater = 2.05138888889
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning vfracintdrop0 = 0.124833333333
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning vfracintdrop = 0.124833333333
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning mxvfracwater = 1.0
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning mnvfracwater = -1.53560989956e-16
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning mxvfracdrop = 1.0
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning mnvfracdrop = -1.34724246013e-176
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning mxvfracair = 1.0
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning mnvfracair = -6.66133814775e-16
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning mxvfracsum = 1.0
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Assigning mnvfracsum = -2.76082612454e-43
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Running failure tests: 
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Running check end time:
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: success.
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Running check end timestep:
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: success.
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Running check water volume fraction was conserved:
conservation error =  1.37667655054e-13
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: success.
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Running check droplet volume fraction was conserved:
conservation error =  1.27953203588e-14
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: success.
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Running check that reasonable tolerance (2.0e-09) is being used to test conservation:
divergence tolerance =  1.39042795135e-09
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: success.
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Running check minimum water volume fraction is 0.0:
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: success.
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Running check maximum water volume fraction is 1.0:
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: success.
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Running check minimum droplet volume fraction is 0.0:
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: success.
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Running check maximum droplet volume fraction is 1.0:
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: success.
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Running check minimum air volume fraction is 0.0:
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: success.
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Running check maximum air volume fraction is 1.0:
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: success.
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Running check minimum sum volume fraction is 0.0:
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: success.
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: Running check maximum sum volume fraction is 1.0:
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: success.
3material-droplet-p1dgp2-test-cty-cv-rhop1dg-3d: PPPPPPPPPPPPP
Passes:   13
Failures: 0
Warnings: 0
```
I build with ```--enable-debugging```.

**Comment by Patol75** [comment]
I am running into something quite weird once more. Different behaviors seem to happen depending this time on the CPU and not on the compiler. I have set up a Ubuntu 18.04 computer for a new PhD student we have in the office. I have set it up in the exact same way as for my 18.04 system. However, there are tests that fail on her system while they pass on mine. An example is ```square-convection-parallel-trivial``` which fails after building from the FixTests branch on the same assertion as previously (Intersection_finder.F90, 211). This assertion failure is supposed to be fixed in this branch, and it does run fine on my system. I am guessing it is a CPU behavior related problem. I am running on an Intel(R) Xeon(R) CPU E5-2630 v4 ( Launch Date Q1'16 ) while she has an Intel® Core™ i7-3770 ( Launch Date Q2'12 ). Any input on this ?

**Comment by jrper** [comment]
I'm afraid chipset dependence is new behaviour as far a we're concerned, but as far as I know, everyone at Imperial is still testing Bionic via a docker container, rather than on bare metal. In the time honoured "have you tried turning off and on again" tradition, does the test failure persist after configuring and building from scratch in a clean checkout?

**Comment by Patol75** [comment]
Well, what I can say is that the machine was running an 18.04 install configured by either @stephankramer or @drhodrid and the tests were failing. What I did is erasing the entire system, installing 18.04 from a Live-Ubuntu, and then setting the machine as I usually do. Fluidity was built from FixTests, and the failures are still here, while they don't occur on my 18.04.

**Comment by Patol75** [comment]
Adding on that, latest commit 564fa66 by @stephankramer on the bionic_workaround branch has probably solved it. However we are having troubles running few parallel tests through testharness (flredecomp seems to only register one process for a command that requires two), but that may also be solved by the latest commit 13051b2 from @jrper on the testharness branch.

**Comment by drhodrid** [comment]
Hi all,

Just following up on Thomas comment. We discovered that the issues he was having with parallel tests were related to conflicting versions of parmetis with zoltan and petsc, in his local build. If we use the petsc and zoltan packages shipped with fluidity-dev under bionic all short tests now pass. I am running medium tests as we speak, but things are looking up.

Best wishes,

Rhod

On 29 May 2018, at 1:44 pm, Thomas Duvernay <notifications@github.com<mailto:notifications@github.com>> wrote:


Adding on that, latest commit 564fa66<https://github.com/FluidityProject/fluidity/commit/564fa669b74aa1908ffa32828f5c7cbd1c694c0d> by @stephankramer<https://github.com/stephankramer> on the bionic_workaround branch has probably solved it. However we are having troubles running few parallel tests through testharness (flredecomp seems to only register one process for a command that requires two), but that may also be solved by the latest commit 13051b2<https://github.com/FluidityProject/fluidity/commit/13051b2b3532a3485d8873bd9ae9ff758eda54c0> from @jrper<https://github.com/jrper> on the testharness branch.

**Comment by drhodrid** [comment]
Medium tests generally look good. 2 failures only:

diamond_validation.xml: FW
gmsh2vtu: F

Is this consistent with the behavior on Jenkins/Docker? 

Rhod

**Comment by Patol75** [comment]
I have memory of @jrper applying a fix for ```diamond_validation.xml```, however that would be interesting to have a look at the log you get out of the failure.

**Comment by stephankramer** [comment]
The diamond_validation failure was indeed fixed by @jrper *somewhere* : it fails if you run it in a checkout that has previously run make test/mediumtest as it finds the junit .xml test summary which obviously doesn't adhere to our test_options schema.
The gmsh2vtu is failure is a bit more cumbersome: some tools (a.o. gmsh2vtu) aren't being linked properly. If you ldd them you can see it can't find the libparmetis.so. This appears to only be happening for tools that don't call petsc_init. If you run `LD_DEBUG=lib ldd gmsh2vtu` you can see that the reason it doesn't find it is that parmetis is only being linked as a secondary to petsc, it looks for its rpath in the rpath of libpetsc.so and that rpath is incorrect. For the tools that do link correctly parmetis is seen as a direct dependency and so it uses the rpath that we give it (which includes the petscdir). Not entirely sure what the best fix is, ideally I would like to fix the petsc package we provide. In principle we could link with the standard Ubuntu 3.7.7 package - except then we need to fix the zoltan package which installs in /usr/lib/petscdir/3.8.3. I will open up a separate issue as I would like to discuss some reorganisation and simplification of these packages.

**Comment by jrper** [comment]
@drhodrid Yes & no. Yes, in the sense of it works on Xenial (see the green tick on the commit in github and the "all checks have passed" message). No in the sense that we don't have a bionic test on Jenkins yet, so that's only been tested locally.

**Comment by Patol75** [comment]
Dear all,
It is nice to see that all the good work made following migrations to Jenkins and Bionic is being merged to master. I am happy to switch to Bionic and report any bug using fluidity master branch. There should not be much in the sense that one PhD student here has already been working on Bionic with alternative branches without any trouble for the past few months. On this side, should the bionic_workaround branch be merged as well ?

**Comment by stephankramer** [comment]
Oh, I thought bionic_workaround was included in FixTests but it seems FixTests is missing 564fa669b74aa1908ffa32828f5c7cbd1c694c0d. Will merge that in as well.

**Pull request merged**
