### PR TITLE
Add support for libsupermesh

### PR DESCRIPTION
**Pull request by iakovos-panourgias**
Add support for libsupermesh (a library for parallel conservative projection between arbitrary meshes).

(https://bitbucket.org/libsupermesh/libsupermesh)

### CODE REVIEW

**Comment by jrmaddison** [comment]
I've made some final changes to this code. Some comments:

- The configure.in code should be closely reviewed for portability.
- The new prescribed_adaptivity_spaces test could potentially replace the existing prescribed_adaptivity test. The new test considers performs more Galerkin projections and considers a greater range of function spaces.
- This includes a couple of bugfixes to the test code (tools/testharness.py and  python/fluidity/regressiontest.py) and a minor fix to femtools/embed_python.c for builds without Python.

**Comment by stephankramer** [comment]
The code all looks great, thanks, @jrmaddison and @iakovos-panourgias .

I have two requests at this point:
1) when I checked out your branch from iakovos-panourgias/fluidity.git:master and tried to push it as a branch to fluidity I noticed there are some very large files that have crept into the git history. Git gives these warnings:

remote: warning: File 3045f0846e3509e36fcbe825edf5852c649b6edd is 86.61 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File ecb6d6d56398dafb68f8b58d116e9197736ba51a is 85.80 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB

That 3045f0846 is tests/prescribed_adaptivity_spaces/src/meshes.tar.bz2 which was indeed 87Mb at some stage of your history. ecb66d5 is tests/libsupermesh_2D/src/files.tar.bz2 which existed at some point at 87Mb. I'm not entirely sure what the easiest way is to purge these from your history...

2) Could you provide a bit more information about what additional (if any) functionality libsupermesh provides for the fluidity user (or other advantages, if any), or if there's any functionality that is available in fluidity's own supermesh but would not be available when configured with libsupermesh. Note that I would be perfectly happy, if there's no advantages at all at the moment (the advantage then being that we could benefit from future improvements to libsupermesh).

**Comment by jrmaddison** [comment]
1) I've purged this file from the repository.
2) Some benefits:

Performance:

The advancing front intersection finder in libsupermesh is, in the largest problems tested in serial benchmarks, 2.7 times faster in 2D and 7.4 times faster in 3D. This is offset somewhat by [issue 6](https://bitbucket.org/libsupermesh/libsupermesh/issues/6/add-optional-element-element-graph), but libsupermesh is still expected to be faster. The new triangle and tetrahedron intersectors are 1.7 times faster in this test.

Maintainability:

The code has been significantly cleaned up. Wild Magic 4 and CGAL related code has been removed, and the Judy library is optional. Use of libspatialindex has been retained, but with a cleaned up interface (which for example now supports multiple R*-trees). libsupermesh has it's own suite of tests with pretty thorough coverage. It has an extensive [manual](https://bitbucket.org/libsupermesh/libsupermesh/downloads/libsupermesh-1.0.0-manual.pdf).

This pull request replaces existing functionality with the use of libsupermesh. However there is additional functionality which could be used in future:

There is an interface for supermeshing in parallel. There are new quad- and oc-tree intersection finders which are around 5 times faster than the R*-tree in the serial benchmark for large problems, although require further testing.

**Comment by jrmaddison** [comment]
Obviously my fix for 1) has caused a problem with the repository (this isn't a 7,326 commit merge). I'll look into fixing this.

**Comment by jrmaddison** [comment]
OK, that should now have been fixed.

**Comment by stephankramer** [comment]
Thanks @jrmaddison and thanks for explaining the benefits. Sounds impressive and very useful.

I've added a buildbot branch here: (currently just builds without libsupermesh)
http://buildbot.ese.ic.ac.uk:8080/builders/libsupermesh

We should add libsupermesh in (at least one of) our test builders. @tmbgreaves would you mind having a look at that?

If all is green I'm happy for it to be merged.

**Comment by tmbgreaves** [comment]
I don't suppose there is a PPA for libsupermesh which I could pick up a Ubuntu package from?

(Might as well ask in case :-) )

**Comment by jrmaddison** [comment]
No, I'm afraid not.

**Comment by tmbgreaves** [comment]
I've debianised it locally but IC have managed to pull the plug on all the system which have my keys on for pushing the package to launchpad, so this will have to wait until next week. Since they have also pulled the plug on buildbot, that's not so much of a problem....

**Comment by tmbgreaves** [comment]
Sorry this has taken so long to get back to - I've added libsupermesh-dev as a dependency of the xenial builder and added --enable-libsupermesh at configure. The builder is running now; assuming it comes back green I'll merge.

**Comment by tmbgreaves** [comment]
One hopefully minor bugfix for a warning out of check_use_statements, suggesting reordering as per:

check_use_statements: Running warning tests: 
check_use_statements: Running Check_use_statements:
../../femtools/Intersection_finder.F90:
  use fldebug
  use quadrature
  use elements
  use parallel_tools
  use data_structures
  use sparse_tools
  use fields_data_types
  use fields_base
  use adjacency_lists
  use linked_lists
  use fields_allocates
  use parallel_fields
  use transform_elements
  use libsupermesh, only : intersections, deallocate, &
& rtree_intersection_finder_reset, &
& rtree_intersection_finder_query_output, &
& rtree_intersection_finder_get_output
  use libsupermesh, only : intersections, deallocate, &
& rtree_intersection_finder_reset, &
& rtree_intersection_finder_query_output, &
& rtree_intersection_finder_get_output
  use supermesh_construction
../../femtools/Supermesh.F90:
  use iso_c_binding, only: c_float, c_double
  use fldebug
  use futils
  use sparse_tools
  use elements
  use fields_data_types
  use fields_base
  use linked_lists
  use fields_allocates
  use fields_manipulation
  use metric_tools
  use unify_meshes_module
  use transform_elements
  use libsupermesh, only : libsupermesh_intersect_elements => intersect_elements
  use tetrahedron_intersection_module

check_use_statements: warning.
check_use_statements: W

**Comment by tmbgreaves** [comment]
Everything else looks fine - and I can trivially fix the ordering once the merge is in, so I'll merge and fix.

**Pull request merged**
