### PR TITLE
Strip libadjoin

### PR DESCRIPTION
**Pull request by slmouradian**
Removes the ability to compile with libadjoint.

Also removes the:
* test_coupler code,
* shallow_water code (note that Shallow water functionality is integrated in Fluidity and is not affected by this merge),
* hybridised helmholtz solver,
* burger's equation solver,

to clear the master Fluidity branch from unused code and remove a redundant dependency (libadjoint).

### CODE REVIEW

**Comment by drhodrid** [comment]
Hi Simon,

I had a look through this today. The code changes largely seem fine to me, but it maybe best that somebody else also has a careful look through. 

One thing I did spot was from line 1018 of aclocal.m4, lots of adjoint stuff remains. I assume this will also need removing or am I missing something?

Note that in addition to the green buildbot I ran short and medium tests locally on my system and everything passed.

R

**Comment by slmouradian** [comment]
Thanks for having a look Rhod, and running the tests. I'll check the aclocal.m4 remnants.

**Comment by drhodrid** [comment]
Any update on this merge?

**Comment by slmouradian** [comment]
pending a review and merge. I'll push to get it done, this week.

**Pull request merged**
