### PR TITLE
Fix Gtk Widget methods deprecation warning in statplot

### PR DESCRIPTION
**Pull request by Patol75**
Two methods have been renamed, I have updated the code accordingly.
Feel free to approve, anyone. :)

### CODE REVIEW

**Comment by stephankramer** [comment]
Looks good, thanks! One query: are the new names also available with older gtk versions on slightly older installs that we might care about?

Note that we're currently experiencing some Jenkins issues (github's not talking to Jenkins) which I believe @tmbgreaves  is looking into...

**Comment by Patol75** [comment]
That is indeed a good question. I have had a look and the doc says that these "new" methods have been introduced with version 3.12, which seems to date back to 2014, which is quite a surprise to me because yesterday was the first day I ran into this deprecation warning. Additionally, I could find mentions of these methods in some GitHub threads in July 2018, which again indicates that we should be pretty safe in terms of backwards compatibility.

**Comment by tmbgreaves** [comment]
Jenkins should be fixed now - sorry for the problems. Short version - we renewed our SSL certificate and I got the certificate chain in the wrong order when reconstructing the keystore...

**Comment by Patol75** [comment]
@tmbgreaves No worries at all, that must have been a nightmare to figure out...

**Review by stephankramer — APPROVED** [review]
Looks good, maybe change the `gi.require_version` on top?

**Comment by Patol75** [comment]
What should I change them to?

**Comment by stephankramer** [comment]
Ah I meant - if we indeed depend on 3.12 now - should it read `require_version('Gtk', '3.12')` ? I don't know, I've never done any gtk stuff

**Comment by Patol75** [comment]
I see, well I have tried it, and it does not seem to be a thing actually. So I will just merge as is for now.

**Pull request merged**
