### PR TITLE
PETSc>=3.9 changes

### PR DESCRIPTION
**Pull request by nkr1729**
MatSolverPackage is now MatSolverType
PCFactorSetMatSolverPackage is now PCFactorSetMatSolverType

Line 139 https://www.mcs.anl.gov/petsc/petsc-3.9/include/petscmat.h.html

### CODE REVIEW

**Comment by nkralpy** [comment]
I just realised that 39eede3 was completely unnecessary.

**Comment by stephankramer** [comment]
Hi there, thanks for contributing!

Fluidity's way of dealing with different petsc version's is a little peculiar. In principle we write to the petsc interface of the latest release (that we support!), and the inconsistencies in previous versions are then dealt with using macros. Have a look at include/petsc_legacy.h to get the idea. This may look a little hacky (and it is!), but the sprinkling of various `#if (PETSC_VERSION_MINOR=...` that we used to do ended up in an unmaintainable mess.

So the idea is that all fluidity source is currently compatible with petsc 3.8. If you want to upgrade our support to 3.9, just change the fortran source files directly (without #ifdefs) to what it should be under 3.9, and then in include/petsc_legacy.h add something like:
```
#if (PETSC_VERSION_MAJOR==3 && PETSC_VERSION_MINOR<9)
#define MatSolverType MatSolverPackage
#endif
```

By the looks of https://www.mcs.anl.gov/petsc/documentation/changes/39.html that seems to be the only change that affects fluidity. Unfortunately support for 3.10 might be a little more work.

Hope this makes sense. If you could try out the above, test it locally with your own petsc 3.9 build by running make shorttest, make mediumtest and make unittest, then once we have our own standard build up and running again we can merge it in master.

**Comment by angus-g** [comment]
I am actually running PETSc 3.11, and other than this issue (and possibly #225) everything seems to work fine. I got a few test failures running on my laptop, but that might also be because I've only got 2 cores available and MPI complains on the oversubscribed tests...

**Comment by Patol75** [comment]
@angus-g I am happy to give it a try on lots of cores if you point me toward the branch I should use.

**Comment by stephankramer** [comment]
@nkr1729 thanks for flagging this up. This is now merged via #224. Let us know if you have any (more) issues with recent versions of petsc. We haven't yet added this to our test suite, so it's possible there are remaining issues - or failing tests with too strict tolerances due to answers slightly changing...

**Pull request closed without merging**
