### PR TITLE
Update vtkfortran for VTK MPI communication.

### PR DESCRIPTION
**Pull request by jrper**
It appears that since about VTK 6.3, their code now uses parallel communication to identify which pieces of a parallel file have been written. See line 213 and onward in their github repository [here](https://github.com/Kitware/VTK/blob/3276be1e1f3d44eb403ebda9ad589869c5b7d4bf/IO/ParallelXML/vtkXMLPDataObjectWriter.cxx). 

The net result on an unlucky setup is that our VTK writers produce a summary .pvtu file referencing only one of the .vtus, even though they have all been written. This changeset attempts to deal with this by doing the necessary work to allow the MPI communication to succeed, but has only been tested locally on one system. Possibly @jmn114 might be able to assist with testing.

### CODE REVIEW

**Comment by stephankramer** [comment]
I think you forgot to commit libvtkfortran/configure

**Comment by jrper** [comment]
Yes, fixed. Actually, more embarrassingly, I forgot to run autoconf to create it, having patched libvtkfortran/include/vtk.h by hand.

**Comment by stephankramer** [comment]
OK, did you actually test this then? :-) Cause it looks we're not actually using libvtkfortran/configure.in (we should probably delete it then) and include/vtk.h actually gets written and copied to vtkfortran by fluidity's own configure.in

**Comment by jrper** [comment]
I tested that the c++ changes fixed the problem with VTK7 on my system, and that the code still configured and ran with the default AMCG packages. I may have neglected to test whether it configured correctly with VTK7 ...

**Comment by stephankramer** [comment]
Good to go after green buildbot:

http://buildbot.ese.ic.ac.uk:8080/waterfall?show=VTK7-parallel

**Comment by jrper** [comment]
This is green and approved, so pushing. @tmbgreaves If I succeed in getting a dockerfile and image which builds VTK 8.1, is there any chance of adding it to buildbot?

**Comment by jrper** [comment]
That was the best soothsaying I could come up with, based on commit dates in the history. If you think it's only higher versions, then we may as well just say VTK 7 and higher. Do you want to make the change and commit it as a bug fix? I suppose it's even possible this might be configure flag dependent...

**Comment by drhodrid** [comment]
Hi James,

Sure thing - I’ll do this tomorrow.

Best wishes,

Rhod

---------------------------------------------------------------------------------------------------
ARC Future Fellow
Research School of Earth Sciences,
The Australian National University,
Mills Road, Acton,
Canberra, ACT, 2601, Australia

T: +61 (0)2 6125 3643
E: rhodri.davies@anu.edu.au<mailto:rhodri.davies@anu.edu.au>
W: http://rses.anu.edu.au/people/dr-rhodri-davies
CRICOS Provider No. 00120C
---------------------------------------------------------------------------------------------------


On 1 May 2018, at 6:08 pm, James Percival <notifications@github.com<mailto:notifications@github.com>> wrote:


That was the best soothsaying I could come up with, based on commit dates in the history. If you think it's only higher versions, then we may as well just say VTK 7 and higher. Do you want to make the change and commit it as a bug fix? I suppose it's even possible this might be configure flag dependent...

**Pull request merged**
