### PR TITLE
Add name of solve to CPU time and Mflop output, such that different s…

### PR DESCRIPTION
**Pull request by drhodrid**
…olves can be more easily identified in the log file.

### CODE REVIEW

**Comment by drhodrid** [comment]
Increased verbosity for solver output (CPU Time spent in solves etc...).

**Comment by jrper** [comment]
My only critique here is that the name is that of the associated scalar(vector/tensor) solution field, which might be a sub optimal tag for individual linear solves. I'm not sure I know a better way to organise it though.

**Comment by drhodrid** [comment]
Hi James,

Thanks for looking at it. I maintained the naming convention that was already used throughout that routine (n/o iterations/ksp converged reason etc…) for consistency. It’s clear enough for what I need.

Best wishes,

Rhod

On 1 Mar 2017, at 01:22, James Percival <notifications@github.com<mailto:notifications@github.com>> wrote:


My only critique here is that the name is that of the associated scalar(vector/tensor) solution field, which might be a sub optimal tag for individual linear solves. I'm not sure I know a better way to organise it though.

**Comment by cianwilson** [comment]
Looks good to me.

**Comment by drhodrid** [comment]
Thanks both. All merged.

**Pull request merged**
