### PR TITLE
Include prescribed fields in checkpoint

### PR DESCRIPTION
**Pull request by drobinson12**
One-line-change to add prescribed fields to checkpoints

### CODE REVIEW

**Comment by drobinson12** [comment]
I have run make test on my local computer and this branch passed.  Tim, do you want to create a Buildbot queue, or are you happy for this to be shipped?

**Comment by tmbgreaves** [comment]
Assuming nobody else objects I'm happy for this to go straight in.

**Comment by cianwilson** [comment]
No objections to this but curious why it is required/desired?

**Comment by cianwilson** [comment]
See now that the option was already in the schema (presumably added accidentally when time averaged diagnostic fields were included) and that this just adds the corresponding functionality to the code.  Still curious why it's useful but assuming it is could the schema documentation (which for prescribed fields still talks about time-averaged diagnostic fields) be updated please?

**Comment by drobinson12** [comment]
In this instance, I'm trying to flredecomp a simulation that prescribes 
a field using a vtu.  As it stood, the code didn't output a partitioned 
version of the input vtu.

**Comment by stephankramer** [comment]
Ah ok, that actually points to a slightly different bug: if you have a prescribed field with the from_file option it should flredecomp that correctly with or without the output/checkpoint option. Actually, you can already get the correct behaviour if you add interpolation options to the prescribed field. If you use adaptivity you will need these anyway, because after an adapt it can't re-prescribe it from a python function as usual, but needs to interpolate from the previous mesh.

In any case it should also adhere to output/checkpoint option. So I'm happy to have this change in - if you could also fix the documentation as Cian requested.

**Comment by fmilthaler** [comment]
Thanks for fixing the documentation in diamon as Cian suggested. This looks good now. Ship it.

**Pull request merged**
