### PR TITLE
More shallow water tests

### PR DESCRIPTION
**Pull request by ctjacobs**
Add some additional shallow water tests:

* swe_dam_break_1d
* swe_dam_break_2d
* swe_tidal_flow_regular_bed
* swe_mms_p2p1_quadratic_drag

Also add a .gitignore file to ignore build files.

### CODE REVIEW

**Comment by stephankramer** [comment]
This is great! More SW tests were desperately needed.

A couple of small comments:
* swe_dam_break_1d: you know there's an analytical solution, right? I think I have some code to compute it, so if you feel virtuous you could make it a bit more rigorous. You could reduce the number of dumps a bit to save disk space.
* swe_dambreak_2d: why did you choose P2P1? Note that it won't be the same as P2P1 in dolfin/firedrake due to the funny masslumping we do. Did you see the weird modes in the velocity solution? Do you get this in dolfin/firedrake as well?
* swe_tidal_flow_regular_bed: the free surface in the final vtu looks very funky. Are you sure this is right?
* swe_mms_p2p1_quadratic_drag: really nice. Did you try running it with more meshes? (not saying you should add those, just curious...)

**Comment by ctjacobs** [comment]
Thanks Stephan.

* swe_tidal_flow_regular_bed: Applying the velocity boundary condition weakly seems to have fixed the issue with the free surface.

* swe_mms_p2p1_quadratic_drag: I've just tried one more run with a finer mesh, and the same order of convergence is observed:

```
Calculating errors for Velocity in A-B convergence test
0.0231625484923
0.024066739517
0.00359526635012
0.00365939927107
swe_mms_p2p1_quadratic_drag: Assigning ab_convergence_vel = [2.6876234369144654, 2.7173619639826683]
Calculating errors for Pressure in A-B convergence test
0.250089563251
0.0567561334517
swe_mms_p2p1_quadratic_drag: Assigning ab_convergence_p = 2.13959663884
Calculating errors for Velocity in B-C convergence test
0.00359526635012
0.00365939927107
0.000522096946888
0.000532696727404
swe_mms_p2p1_quadratic_drag: Assigning bc_convergence_vel = [2.783709027354837, 2.7802205114481846]
Calculating errors for Pressure in B-C convergence test
0.0567561334517
0.0134126291944
swe_mms_p2p1_quadratic_drag: Assigning bc_convergence_p = 2.0811842407
Calculating errors for Velocity in B-C convergence test
0.000522096946888
0.000532696727404
7.25127830001e-05
7.32530069138e-05
swe_mms_p2p1_quadratic_drag: Assigning cd_convergence_vel = [2.8480104723082014, 2.862354531712997]
Calculating errors for Pressure in B-C convergence test
0.0134126291944
0.00325325116996
```

This takes a very long time to run though, so I won't add it.

* swe_dam_break_2d: I chose P2-P1 since it was the only stable element pair that I could use with Firedrake-Fluids at the time. I thought I'd make the Fluidity setup as consistent as possible. However, I do indeed see the weird velocity modes as a result of the mass lumping. This isn't the case with Firedrake-Fluids.

* swe_dam_break_1d: I have a script which can compute the analytical solution, but I didn't get round to hooking it up to the pass_tests. I've now reduced the dump period to save disk space.

**Comment by ctjacobs** [comment]
Can this be merged please?

**Comment by stephankramer** [comment]
Just had another look, I now see this adds a .gitignore file. Happy to discuss the pros and cons of having one, but can we do that on another PR please?

One last nit-pick: the fluidity command should be explicitly in the .xml file (as should flredecomp and anything else that potentially has to run in parallel). This is so we can mangle it when it needs to run on various non-standard platforms (e.g. cx1).

Other than, it all looks great. Thanks a lot for adding these tests. This is really useful.

**Comment by ctjacobs** [comment]
Thanks @stephankramer. I've now removed the `.gitignore` file and placed the `fluidity` commands in the .xml files.

@tmbgreaves, the build queue for the `shallow-water-tests` branch no longer exists - can this be recovered please?

**Comment by tmbgreaves** [comment]
Done:

http://buildbot.ese.ic.ac.uk:8080/builders/shallow-water-tests

**Comment by ctjacobs** [comment]
Great - thank you Tim. This still has a green light (http://buildbot.ese.ic.ac.uk:8080/builders/shallow-water-tests/builds/2) so I'll merge.

**Pull request merged**
