### PR TITLE
Fix libnetcdff configure

### PR DESCRIPTION
**Pull request by jrper**
This changeset attempts to improve the behaviour of the configure script in searching for the netcdf Fortan interface library (libnetcdff). Without these changes, there are issues with the shared library build.

### CODE REVIEW

**Comment by stephankramer** [comment]
Should you commit configure as well?

**Comment by jrper** [comment]
... oops.

**Comment by tmbgreaves** [comment]
That looks entirely sane to me; very happy for it to go in assuming buildbot is happy:

http://buildbot.ese.ic.ac.uk:8080/builders/fix_netcdff_configure

**Comment by jrper** [comment]
Buildbot matches master (the failure is one Tim has fixed elsewhere), so I'm merging this.

**Pull request merged**
