### PR TITLE
Lagrangian detector issues

### LINKED ISSUE #126: Lagrangian detectors in parallel: seg faults and assertion failures
Hi all,

A student of mine (Tim Jones) has recently been running a series of simulations where Lagrangian detectors are utilized for a range of models diagnostics. He is finding that simulations incorporating these detectors are incredibly temperamental, with segmentation faults and a number of assertion failures commonly observed inside detector subroutines, particularly as the number of detectors is increased. I have tried to generate some minimal reproducers for these features (his simulations are typically run across hundreds of cores, which makes debugging a challenge!) and have managed to come up with the first one (a segmentation fault during parallel detector exchange) today, hence this report. 

In the branch lagrangian_detector_issues, I have modified the lagrangian_detector_3d test to include 100,000 detectors (a reasonably small number) and a slightly finer mesh resolution than was previously the case. The simulation is setup to run on 2 cores and produces a segmentation fault when exchanging detectors between cores. I have included a back-trace below. Any ideas what is going on? I have verified that this case runs fine on a single core. 

I'll keep going on reproducing the cases that fail various asserts, but would be interested to hear if others have experienced similar issues with detectors (in parallel)... and if this is a simple fix or something more complex...

_#0  __memcpy_sse2_unaligned ()
    at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:35
#1  0x00007fffd3158558 in ?? ()
   from /usr/lib/openmpi/lib/openmpi/mca_btl_vader.so
#2  0x00007fffd270f948 in mca_pml_ob1_send_request_schedule_once ()
   from /usr/lib/openmpi/lib/openmpi/mca_pml_ob1.so
#3  0x00007fffd270a258 in mca_pml_ob1_recv_frag_callback_ack ()
   from /usr/lib/openmpi/lib/openmpi/mca_pml_ob1.so
#4  0x00007fffd3159813 in mca_btl_vader_poll_handle_frag ()
   from /usr/lib/openmpi/lib/openmpi/mca_btl_vader.so
#5  0x00007fffd3159cc3 in ?? ()
   from /usr/lib/openmpi/lib/openmpi/mca_btl_vader.so
#6  0x00007fffea9731ea in opal_progress () from /usr/lib/libopen-pal.so.13
#7  0x00007ffff3e56f65 in ompi_request_default_wait_all ()
   from /usr/lib/libmpi.so.12
#8  0x00007ffff3e87d27 in PMPI_Waitall () from /usr/lib/libmpi.so.12
#9  0x00007ffff476b46a in pmpi_waitall__ () from /usr/lib/libmpi_mpifh.so.12
#10 0x000000000059e9d0 in detector_parallel::exchange_detectors (state=..., 
    detector_list=..., send_list_array=...) at Detector_Parallel.F90:446
#11 0x000000000059f83c in detector_parallel::distribute_detectors (state=..., 
    detector_list=...) at Detector_Parallel.F90:189
#12 0x00000000013a24fb in detector_move_lagrangian::move_lagrangian_detectors (
    state=..., detector_list=..., dt=0.10000000000000001, timestep=61_

### PR DESCRIPTION
**Pull request by drhodrid**
This branch fixes #126, one (I think there could be more) of the bugs with parallel lagrangian detectors. My thanks go to Lawrence Mitchell for the fix. 

Note that I have also updated the lagrangian_detector_3d test to make it a little more challenging (and adaptable for different numbers of detectors). 

If this needs to be run through buildbot could somebody please set up a queue and trigger the build? 

Nos da!

Rhod

### CODE REVIEW

**Comment by wence-** [comment]
I can't comment on the test changes, but my reading of the MPI standard suggests that this is the correct fix for the detector exchange code.

**Comment by stephankramer** [comment]
Buildbot queue: http://buildbot.ese.ic.ac.uk:8080/waterfall?show=lagrangian_detector_issues

**Comment by stephankramer** [comment]
Test changes like fine. One query though: did you time how long the test now takes? As processing 100,000 detectors might take a while...

**Comment by drhodrid** [comment]
Thanks Steph and good spot on the timing. The test takes about 130 seconds on my system. I'll move it across to a medium test.

**Comment by jrper** [comment]
Is there any chance of splitting it in two and leaving a short version that runs the original test? It's kind of convenient to me having that code branch exercised in the  short tests...

**Comment by drhodrid** [comment]
Hi Percy,

I've done this, as requested. Will merge into master once Buildbot gives me the green light... although it seems to be playing up right now.

Rhod

**Comment by tmbgreaves** [comment]
Sorry about that - we appear to have lost one of our builders. I've redirected all the branch builds over to buildbot-2 which should be fine to handle them for now.

**Comment by jrper** [comment]
Could I ask how large a file this branch now creates when running the medium tests?

**Comment by stephankramer** [comment]
Yes, that's a very good point: I don't think we should have short or medium tests that create GBs of data. Also, thanks for trying to shorten it, but I think 17min on 8 cores (of presumably a newish machine) is still a bit too much for medium. So I would suggest making it long.

**Comment by drhodrid** [comment]
OK - I have transferred the test across to longtests, as requested. I have triggered buildbot, but will be away for the next week or so. When it turns green (I'm optimistic!), could somebody please merge the branch? @tmbgreaves  - I'm not sure what I need to do for the longtests, but the lagrangian_detector_3d_2e5 test has been committed to the longtests repo, so I guess its over to you.

**Comment by tmbgreaves** [comment]
Thanks Rhod. I'll merge assuming it goes green. Long tests pick up automatically on their own queue and run about once every two weeks.

**Pull request merged**
